export enum AccessLevel {
  ACCOUNT_OFFICER = '10',
  ADK_PUSAT_CABANG = '20',
  CBL_PINCA_PINCAPEM_WAPINCA_MP = '30',
  KADIV_WAKADIV_RBO_SLP_LPM_ARK = '40',
  KABAG_STAFF_RBO_SLP = '50',
  MONITORING_LEVEL = '90',
  ADMINISTRATOR = '99',
}
